# Generated by Django 2.0 on 2018-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiducial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PUID', models.UUIDField()),
                ('location', models.CharField(max_length=1)),
                ('pair', models.IntegerField()),
                ('template', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PointSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.UUIDField()),
                ('date', models.DateTimeField(verbose_name='Date of landmarking')),
                ('session', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('template', models.CharField(max_length=200)),
                ('error', models.FileField(max_length=200, upload_to=None)),
                ('point', models.FileField(max_length=200, upload_to=None)),
            ],
        ),
    ]
